import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { api } from './api';
import { toast } from 'sonner';
import type {Bootstrap,Product,Category} from './types';
type Draft={addressId?:string;shippingMethod?:string;paymentMethod?:string;coupon?:string;note?:string};
type State=Partial<Bootstrap>&{products:Product[];ready:boolean;error:string;busy:number;theme:'light'|'dark';onboarded:boolean;searches:string[];category:Category;checkoutDraft:Draft;guestCartDraft:{productId:string;quantity:number;size:string;color:string}[];init:()=>Promise<void>;refresh:()=>Promise<void>;sync:(data:Bootstrap)=>void;perform:<T=any>(path:string,method?:string,body?:unknown)=>Promise<T>;setTheme:(theme:'light'|'dark')=>void;setOnboarded:()=>void;addSearch:(s:string)=>void;clearSearch:(s?:string)=>void;setCategory:(c:Category)=>void;setDraft:(d:Draft)=>void};
const safeStorage={getItem:(key:string)=>{try{return localStorage.getItem(key)}catch{return null}},setItem:(key:string,value:string)=>{try{localStorage.setItem(key,value)}catch{/* Preferences stay in memory when storage is unavailable. */}},removeItem:(key:string)=>{try{localStorage.removeItem(key)}catch{}}};
export const useApp=create<State>()(persist((set,get)=>({products:[],ready:false,error:'',busy:0,theme:'light',onboarded:false,searches:[],category:'All',checkoutDraft:{},guestCartDraft:[],
 sync:(data)=>{const previous=get();if(previous.ready&&data.notifications.some(n=>!n.read&&!previous.notifications?.some(old=>old.id===n.id))){const prefs=data.user.settings;if(prefs.general!==false){if(prefs.vibrate!==false&&typeof navigator.vibrate==='function')navigator.vibrate(35);if(prefs.sound!==false&&navigator.userActivation?.isActive){try{const audio=new AudioContext();const oscillator=audio.createOscillator(),gain=audio.createGain();gain.gain.value=.035;oscillator.frequency.value=660;oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.09);oscillator.onended=()=>void audio.close()}catch{}}}}set({...data,guestCartDraft:data.user.guest?data.cart.map(l=>({productId:l.productId,quantity:l.quantity,size:l.size,color:l.color})):[]})},
 init:async()=>{set({error:''});try{const results=await Promise.allSettled([api<Bootstrap>('/bootstrap'),api<Product[]>('/products')]);for(const r of results)if(r.status==='rejected')throw r.reason;const state=results[0]as PromiseFulfilledResult<Bootstrap>;const products=results[1]as PromiseFulfilledResult<Product[]>;get().sync(state.value);set({products:products.value,ready:true})}catch(e){set({error:(e as Error).message,ready:false})}},
 refresh:async()=>{try{const data=await api<Bootstrap>('/bootstrap');get().sync(data)}catch(e){toast.error((e as Error).message);throw e}},
 perform:async(path,method='POST',body)=>{set(s=>({busy:s.busy+1}));try{const result=await api(path,method,body);if(result.user&&result.cart)get().sync(result);if(result.state)get().sync(result.state);if(path==='/checkout'||path.endsWith('/cancel')||path.endsWith('/reviews')){try{set({products:await api<Product[]>('/products')})}catch{}}return result}catch(e){toast.error((e as Error).message);throw e}finally{set(s=>({busy:Math.max(0,s.busy-1)}))}},
 setTheme:theme=>set({theme}),setOnboarded:()=>set({onboarded:true}),addSearch:s=>set(state=>({searches:[s,...state.searches.filter(v=>v!==s)].slice(0,8)})),clearSearch:s=>set(state=>({searches:s?state.searches.filter(v=>v!==s):[]})),setCategory:category=>set({category}),setDraft:d=>set(s=>({checkoutDraft:{...s.checkoutDraft,...d}})),
}),{name:'evira-device-v1',version:1,storage:createJSONStorage(()=>safeStorage),partialize:s=>({theme:s.theme,onboarded:s.onboarded,searches:s.searches,category:s.category,checkoutDraft:s.checkoutDraft,guestCartDraft:s.guestCartDraft}),merge:(saved,current)=>{const p=(saved??{})as Partial<State>;return{...current,theme:p.theme==='dark'?'dark':'light',onboarded:p.onboarded===true,searches:Array.isArray(p.searches)?p.searches.filter(s=>typeof s==='string').slice(0,8):[],category:p.category??'All',checkoutDraft:p.checkoutDraft&&typeof p.checkoutDraft==='object'?p.checkoutDraft:{},guestCartDraft:Array.isArray(p.guestCartDraft)?p.guestCartDraft:[]}}}));
export const categories:Category[]=['All','Clothing','Shoes','Bags','Electronics','Watches','Eyewear','Jewelry','Toys'];
