import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {createRuntime} from '../scripts/local-runtime.mjs';
import {randomUUID} from 'node:crypto';
let mf;
before(async()=>{mf=await createRuntime({persist:false})});
after(async()=>{await mf?.dispose()});
function client(){let cookie='';return{async request(path,method='GET',body){const r=await mf.dispatchFetch('http://localhost:4173/api'+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return{status:r.status,data:await r.json()}},get cookie(){return cookie}}}
test('end-to-end shopping, wallet, account, and ownership invariants',async t=>{
 const alice=client(),bob=client();let state,products,orderId,originalStock,checkoutInput;
 await t.test('bootstrap seeds all catalog categories and isolated guest accounts',async()=>{const a=await alice.request('/bootstrap'),b=await bob.request('/bootstrap');assert.equal(a.status,200);assert.equal(b.status,200);state=a.data;assert.notEqual(a.data.user.id,b.data.user.id);assert.equal(state.user.balance,937900);assert.equal(state.transactions[0].amount,937900);const p=await alice.request('/products');assert.equal(p.data.length,24);products=p.data;assert.ok(p.data.find(p=>p.category==='Jewelry'));assert.ok(p.data.find(p=>p.category==='Toys'));assert.equal(state.orders.length,2);assert.ok(!('passwordHash'in state.user));});
 await t.test('existing demo galleries gain alternate views without overwriting product data',async()=>{
  const db=await mf.getD1Database('DB'),puma=products.find(p=>p.id==='p01'),bag=products.find(p=>p.id==='p06');
  assert.deepEqual(puma.images,['/images/sneaker-puma.webp','/images/sneaker-puma-2.webp']);
  const customImages=[bag.image,'/images/custom-view.webp'];
  await db.batch([
   db.prepare('UPDATE "Product" SET "images"=? WHERE "id"=?').bind(JSON.stringify([puma.image]),puma.id),
   db.prepare('UPDATE "Product" SET "images"=? WHERE "id"=?').bind(JSON.stringify(customImages),bag.id),
  ]);
  const next=(await alice.request('/products')).data,repaired=next.find(p=>p.id===puma.id);
  assert.deepEqual(repaired.images,puma.images);
  assert.equal(repaired.stock,puma.stock);
  assert.equal(repaired.price,puma.price);
  assert.equal(repaired.sold,puma.sold);
  assert.deepEqual(next.find(p=>p.id===bag.id).images,customImages);
  await db.prepare('UPDATE "Product" SET "images"=? WHERE "id"=?').bind(JSON.stringify([]),bag.id).run();
  const again=(await alice.request('/products')).data;
  assert.deepEqual(again.find(p=>p.id===bag.id).images,bag.images);
 });
 await t.test('wishlist persists and toggles',async()=>{const a=await alice.request('/wishlist/p01','POST');assert.deepEqual(a.data.wishlist,['p01']);const b=await alice.request('/bootstrap');assert.deepEqual(b.data.wishlist,['p01']);const c=await alice.request('/wishlist/p01','POST');assert.deepEqual(c.data.wishlist,[])});
 await t.test('invalid variants and oversized cart lines are rejected',async()=>{assert.equal((await alice.request('/cart','POST',{productId:'p01',size:'not-a-size',color:'Original',quantity:1})).status,400);assert.equal((await alice.request('/cart','POST',{productId:'p01',size:'38',color:'Original',quantity:21})).status,400)});
 await t.test('distinct variants survive reload and cart updates',async()=>{const base={productId:'p01',size:'38',color:'Original',quantity:1};assert.equal((await alice.request('/cart','POST',base)).status,200);const a=await alice.request('/cart','POST',{...base,size:'39'});assert.equal(a.data.cart.length,2);const line=a.data.cart.find(l=>l.size==='38');const b=await alice.request('/cart/'+line.id,'PATCH',{quantity:2});assert.equal(b.data.cart.find(l=>l.id===line.id).quantity,2);assert.equal((await bob.request('/cart/'+line.id,'PATCH',{quantity:4})).status,404);state=(await alice.request('/bootstrap')).data;assert.equal(state.cart.length,2)});
 await t.test('server validates coupons and owns quote totals',async()=>{const q=await alice.request('/checkout/quote','POST',{shippingMethod:'regular',coupon:'WELCOME30'});assert.equal(q.status,200);assert.equal(q.data.subtotal,products.find(p=>p.id==='p01').price*3);assert.equal(q.data.discount,Math.min(Math.round(q.data.subtotal*.3),5000));assert.equal(q.data.total,q.data.subtotal-q.data.discount+1000);assert.equal((await alice.request('/checkout/quote','POST',{coupon:'FAKE'})).status,400)});
 await t.test('checkout commits order, stock and wallet together and is idempotent',async()=>{originalStock=products.find(p=>p.id==='p01').stock;const old=state.user.balance;checkoutInput={addressId:state.addresses[0].id,shippingMethod:'regular',paymentMethod:'wallet',coupon:'WELCOME30',idempotencyKey:randomUUID()};const result=await alice.request('/checkout','POST',{...checkoutInput,total:1});assert.equal(result.status,201);orderId=result.data.order.id;assert.equal(result.data.state.cart.length,0);assert.equal(result.data.state.user.balance,old-result.data.order.total);const after=(await alice.request('/products')).data.find(p=>p.id==='p01');assert.equal(after.stock,originalStock-3);const duplicate=await alice.request('/checkout','POST',checkoutInput);assert.equal(duplicate.status,200);assert.equal(duplicate.data.order.id,orderId);assert.equal(duplicate.data.state.user.balance,result.data.state.user.balance);assert.equal((await bob.request('/orders/'+orderId)).status,404);});
 await t.test('cancel restocks exactly once and refunds wallet exactly once',async()=>{const a=await alice.request('/orders/'+orderId+'/cancel','POST');assert.equal(a.status,200);assert.equal(a.data.user.balance,937900);assert.equal(a.data.transactions.filter(tx=>tx.type==='refund').length,1);const b=await alice.request('/orders/'+orderId+'/cancel','POST');assert.equal(b.data.user.balance,937900);assert.equal((await alice.request('/products')).data.find(p=>p.id==='p01').stock,originalStock)});
 await t.test('wallet topup validates payment ownership and duplicate protection',async()=>{state=(await alice.request('/bootstrap')).data;const b=(await bob.request('/bootstrap')).data;const base={amount:10000,paymentMethod:state.payments[0].id,idempotencyKey:randomUUID()};assert.equal((await bob.request('/wallet/topup','POST',base)).status,400);const a=await alice.request('/wallet/topup','POST',base);assert.equal(a.data.user.balance,947900);const again=await alice.request('/wallet/topup','POST',base);assert.equal(again.data.user.balance,947900);assert.equal((await alice.request('/wallet/topup','POST',{...base,amount:-100,idempotencyKey:randomUUID()})).status,400)});
 await t.test('wallet PIN protects topups and PIN replacement',async()=>{assert.equal((await alice.request('/security/pin','POST',{pin:'123456'})).status,200);state=(await alice.request('/bootstrap')).data;assert.equal(state.user.hasPin,true);const base={amount:100,paymentMethod:state.payments[0].id,idempotencyKey:randomUUID()};assert.equal((await alice.request('/wallet/topup','POST',{...base,pin:'000000'})).status,403);assert.equal((await alice.request('/wallet/topup','POST',{...base,pin:'123456'})).status,200);assert.equal((await alice.request('/security/pin','POST',{pin:'654321',currentPin:'000000'})).status,403);assert.equal((await alice.request('/security/pin','POST',{pin:'654321',currentPin:'123456'})).status,200)});
 await t.test('insufficient balance leaves stock, cart, wallet and orders unchanged',async()=>{await alice.request('/cart','POST',{productId:'p19',size:'One size',color:'Original',quantity:20});const before=(await alice.request('/bootstrap')).data;const stock=(await alice.request('/products')).data.find(p=>p.id==='p19').stock;const result=await alice.request('/checkout','POST',{addressId:before.addresses[0].id,shippingMethod:'express',paymentMethod:'wallet',pin:'654321',idempotencyKey:randomUUID()});assert.equal(result.status,400);const after=(await alice.request('/bootstrap')).data;assert.equal(after.user.balance,before.user.balance);assert.equal(after.orders.length,before.orders.length);assert.equal(after.cart.length,before.cart.length);assert.equal((await alice.request('/products')).data.find(p=>p.id==='p19').stock,stock);await alice.request('/cart/'+after.cart[0].id,'DELETE')});
 await t.test('review requires delivery, delivery cannot cancel, and review likes toggle',async()=>{assert.equal((await alice.request('/products/p03/reviews','POST',{rating:5,text:'Nice product'})).status,403);await alice.request('/cart','POST',{productId:'p03',size:'One size',color:'Original',quantity:1});state=(await alice.request('/bootstrap')).data;const result=await alice.request('/checkout','POST',{addressId:state.addresses[0].id,shippingMethod:'economy',paymentMethod:state.payments[0].id,idempotencyKey:randomUUID()});assert.equal(result.status,201);const oid=result.data.order.id;await alice.request('/orders/'+oid+'/advance','POST');await alice.request('/orders/'+oid+'/advance','POST');assert.equal((await alice.request('/orders/'+oid+'/cancel','POST')).status,400);await alice.request('/orders/'+oid+'/advance','POST');assert.equal((await alice.request('/products/p03/reviews','POST',{rating:4,text:'Comfortable headphones. Demo review.'})).status,200);const reviews=(await alice.request('/products/p03/reviews')).data;assert.equal(reviews.length,1);assert.equal(reviews[0].rating,4);const like=await alice.request('/reviews/'+reviews[0].id+'/like','POST');assert.equal(like.data.likes,1);assert.equal((await alice.request('/reviews/'+reviews[0].id+'/like','POST')).data.likes,0)});
 await t.test('address CRUD and settings persist and enforce ownership',async()=>{const data={label:'Work',recipient:'Alex',phone:'+85512345678',line1:'Office 7, Street 51',city:'Phnom Penh',country:'Cambodia',postalCode:'120101',isDefault:true};const a=await alice.request('/addresses','POST',data);assert.equal(a.status,200);const addr=a.data.addresses.find(a=>a.label==='Work');assert.equal(a.data.addresses.filter(a=>a.isDefault).length,1);assert.equal((await bob.request('/addresses/'+addr.id,'PATCH',data)).status,404);const b=await alice.request('/addresses/'+addr.id,'PATCH',{...data,line1:'Office 8, Street 51'});assert.equal(b.data.addresses.find(a=>a.id===addr.id).line1,'Office 8, Street 51');const c=await alice.request('/addresses/'+addr.id,'DELETE');assert.equal(c.data.addresses.length,1);assert.equal(c.data.addresses[0].isDefault,true);const settings=await alice.request('/settings','PATCH',{language:'Khmer',general:false});assert.equal(settings.data.user.settings.language,'Khmer');assert.equal(settings.data.user.settings.general,false)});
 await t.test('messages save complete conversations; notifications mark read',async()=>{const a=await alice.request('/messages','POST',{text:'How do I track my order?',channel:'support'});assert.equal(a.status,200);assert.ok(a.data.at(-1).text.includes('My Orders'));assert.equal((await alice.request('/messages')).data.length,a.data.length);assert.equal((await bob.request('/messages','POST',{text:'Hi',channel:'courier:'+orderId})).status,404);const n=await alice.request('/notifications','PATCH',{});assert.ok(n.data.notifications.every(n=>n.read))});
 await t.test('guest account upgrades, logout/login preserve data, reset invalidates old password',async()=>{state=(await alice.request('/bootstrap')).data;const accountEmail='alice-'+randomUUID()+'@example.com';const reg=await alice.request('/auth/register','POST',{name:'Alice Example',email:accountEmail,password:'CorrectPass123!',rememberMe:false});assert.equal(reg.status,200);assert.equal(reg.data.user.id,state.user.id);assert.equal(reg.data.user.guest,false);assert.equal(reg.data.orders.length,state.orders.length);assert.equal((await alice.request('/auth/logout','POST')).status,200);assert.equal((await alice.request('/auth/login','POST',{email:accountEmail,password:'WrongPassword!'})).status,401);const login=await alice.request('/auth/login','POST',{email:accountEmail,password:'CorrectPass123!'});assert.equal(login.status,200);assert.equal(login.data.user.id,state.user.id);const forgot=await alice.request('/auth/forgot','POST',{email:accountEmail,method:'email'});assert.equal(forgot.status,200);assert.equal((await alice.request('/auth/reset','POST',{challengeId:forgot.data.challengeId,code:'000000',password:'NewPass123!'})).status,400);assert.equal((await alice.request('/auth/reset','POST',{challengeId:forgot.data.challengeId,code:forgot.data.demoCode,password:'NewPass123!'})).status,200);await alice.request('/auth/logout','POST');assert.equal((await alice.request('/auth/login','POST',{email:accountEmail,password:'CorrectPass123!'})).status,401);assert.equal((await alice.request('/auth/login','POST',{email:accountEmail,password:'NewPass123!'})).status,200)});
 await t.test('competing checkouts cannot oversell or debit the losing shopper',async()=>{const a=client(),b=client();const sa=(await a.request('/bootstrap')).data,sb=(await b.request('/bootstrap')).data;const db=await mf.getD1Database('DB');await db.prepare('UPDATE "Product" SET "stock"=1 WHERE "id"=?').bind('p24').run();for(const shopper of [a,b])assert.equal((await shopper.request('/cart','POST',{productId:'p24',size:'One size',color:'Original',quantity:1})).status,200);const results=await Promise.all([a.request('/checkout','POST',{addressId:sa.addresses[0].id,shippingMethod:'economy',paymentMethod:'wallet',idempotencyKey:randomUUID()}),b.request('/checkout','POST',{addressId:sb.addresses[0].id,shippingMethod:'economy',paymentMethod:'wallet',idempotencyKey:randomUUID()})]);assert.equal(results.filter(r=>r.status===201).length,1);assert.ok(results.some(r=>[400,409].includes(r.status)));const loser=results[0].status===201?b:a;const unchanged=(await loser.request('/bootstrap')).data;assert.equal(unchanged.user.balance,937900);assert.equal(unchanged.cart.length,1);assert.equal(unchanged.orders.length,2);assert.equal((await a.request('/products')).data.find(p=>p.id==='p24').stock,0)});
 await t.test('notification preferences suppress new notices',async()=>{const a=client();let state=(await a.request('/bootstrap')).data;await a.request('/settings','PATCH',{general:false});const result=await a.request('/wallet/topup','POST',{amount:100,paymentMethod:state.payments[0].id,idempotencyKey:randomUUID()});assert.equal(result.status,200);assert.equal(result.data.notifications.length,state.notifications.length)});
 await t.test('cross-origin cookie writes are rejected',async()=>{const r=await mf.dispatchFetch('http://localhost:4173/api/cart',{method:'POST',headers:{Origin:'https://attacker.invalid',Cookie:alice.cookie,'Content-Type':'application/json'},body:JSON.stringify({productId:'p01',size:'38',color:'Original',quantity:1})});assert.equal(r.status,403)});
});
