import { Hono } from 'hono';
import { getCookie, setCookie, deleteCookie } from 'hono/cookie';
import { HTTPException } from 'hono/http-exception';
import { z } from 'zod';
import { generateRegistrationOptions, verifyRegistrationResponse, generateAuthenticationOptions, verifyAuthenticationResponse } from '@simplewebauthn/server';
import { database, seedCatalog, parse, product, order, publicUser, type Env } from './db';
import { id, hash, verify, digest, b64, bytes } from './crypto';
import { coupons, shippingMethods } from './catalog';
const app=new Hono<{Bindings:Env;Variables:{db:ReturnType<typeof database>;user:any;sessionId:string}}>();
function fail(message:string,status:400|401|403|404|409|429=400):never{throw new HTTPException(status,{message})}
const text=(max=120)=>z.string().trim().min(1).max(max);
const iso=()=>new Date().toISOString();
const email=z.string().trim().email().max(160).transform(v=>v.toLowerCase());
const password=z.string().min(8,'Use at least 8 characters.').max(128);
const pin=z.string().regex(/^\d{6}$/,'Enter a 6-digit PIN.');
async function session(c:any,userId:string,remember=true){const token=id()+id();const sid=await digest(token);await c.get('db').session.create({data:{id:sid,userId,expiresAt:new Date(Date.now()+(remember?30:1)*864e5)}});setCookie(c,'evira_session',token,{httpOnly:true,secure:new URL(c.req.url).protocol==='https:',sameSite:'Lax',path:'/',maxAge:remember?30*86400:undefined});return sid}
async function limit(c:any,key:string,max=12){const db=c.get('db');const challengeId='limit:'+await digest(key);const old=await db.authChallenge.findUnique({where:{id:challengeId}});if(old&&new Date(old.expiresAt)>new Date()){if(old.attempts>=max)fail('Too many attempts. Try again in 10 minutes.',429);await db.authChallenge.update({where:{id:challengeId},data:{attempts:{increment:1}}})}else await db.authChallenge.upsert({where:{id:challengeId},create:{id:challengeId,userId:'rate-limit',type:'rate-limit',value:'',attempts:1,expiresAt:new Date(Date.now()+600000)},update:{attempts:1,expiresAt:new Date(Date.now()+600000)}})}
async function authorizePin(c:any,value?:string){const u=c.get('user');if(u.pinHash){await limit(c,'pin:'+u.id,8);if(!value||!await verify(value,u.pinHash))fail('The PIN is incorrect.',403)}}
async function notify(c:any,title:string,body:string,link='/orders'){const prefs=parse(c.get('user').settings,{});const category=link==='/wallet'?'payment':link.startsWith('/orders')?'updates':link==='/offers'?'promotions':'general';if(prefs.general===false||prefs[category]===false)return;await c.get('db').notification.create({data:{id:id(),userId:c.get('user').id,title,text:body,link}})}
async function bootstrap(c:any){const db=c.get('db'),uid=c.get('user').id;const [u,cart,wishlist,addresses,payments,orders,transactions,notifications,keys]=await Promise.all([db.user.findUniqueOrThrow({where:{id:uid}}),db.cartItem.findMany({where:{userId:uid},include:{product:{include:{_count:{select:{reviews:true}}}}}}),db.wishlist.findMany({where:{userId:uid}}),db.address.findMany({where:{userId:uid},orderBy:{isDefault:'desc'}}),db.paymentMethod.findMany({where:{userId:uid}}),db.order.findMany({where:{userId:uid},orderBy:{createdAt:'desc'},take:100}),db.walletTransaction.findMany({where:{userId:uid},orderBy:{createdAt:'desc'},take:100}),db.notification.findMany({where:{userId:uid},orderBy:{createdAt:'desc'},take:100}),db.passkey.count({where:{userId:uid}})]);return{user:publicUser(u,keys),cart:cart.map((x:any)=>({...x,product:product(x.product)})),wishlist:wishlist.map((x:any)=>x.productId),addresses,payments,orders:orders.map(order),transactions,notifications}}
async function createDemo(c:any,name='Alex Morgan',provider?:string){const db=c.get('db'),uid=id();const u=await db.user.create({data:{id:uid,email:uid+'@guest.evira.local',name,phone:'+855 12 345 678',settings:JSON.stringify({language:'English',general:true,sound:true,vibrate:true,promotions:true,updates:true,payment:true}),guest:true}});await session(c,uid);c.set('user',u);
 const address=await db.address.create({data:{id:id(),userId:uid,label:'Home',recipient:name,phone:'+855 12 345 678',line1:'21 Street 302, Boeung Keng Kang',city:'Phnom Penh',country:'Cambodia',postalCode:'120102',isDefault:true}});
 await db.paymentMethod.create({data:{id:id(),userId:uid,brand:'Visa',last4:'4242',name,expiry:'12/30'}});
 await db.walletTransaction.create({data:{id:id(),userId:uid,title:'Welcome demo balance',amount:937900,type:'topup',reference:'welcome:'+uid}});
 const all=await db.product.findMany({take:6});
 for(const [index,status]of ['processing','delivered'].entries()){
  const p=all[index];if(!p)continue;const oid='demo-'+id(),time=new Date(Date.now()-(index+1)*3*864e5).toISOString();const item={productId:p.id,name:p.name,image:p.image,size:parse(p.sizes)[0],color:parse(p.colors)[0],quantity:1,price:p.price};
  await db.order.create({data:{id:oid,userId:uid,cartVersion:-index-1,idempotencyKey:oid,status,items:JSON.stringify([item]),subtotal:p.price,discount:0,shipping:1000,total:p.price+1000,address:JSON.stringify(address),shippingMethod:'regular',paymentMethod:'Demo Visa •••• 4242',events:JSON.stringify([{status:'placed',time,text:'Sample order placed'},{status,time:iso(),text:status==='delivered'?'Sample parcel delivered':'Sample parcel is being prepared'}]),createdAt:new Date(time)}});
 }
 await db.notification.create({data:{id:id(),userId:uid,title:'Welcome to Evira',text:provider?`You are trying the ${provider} sign-in simulation. No provider account is connected.`:'Your demo account includes sample orders and a demo wallet. Browse, shop and explore.',link:'/'}});
 await db.message.create({data:{id:id(),userId:uid,text:'Hi! I’m the Evira demo assistant. How can I help with your order today?',sender:'assistant',channel:'support'}});
 return u;
}
app.use('/api/*',async(c,next)=>{c.header('Cache-Control','no-store');const origin=c.req.header('Origin');if(!['GET','HEAD','OPTIONS'].includes(c.req.method)&&origin&&origin!==new URL(c.req.url).origin)fail('This request was blocked.',403);c.set('db',database(c.env));const cookie=getCookie(c,'evira_session');if(cookie){const sid=await digest(cookie);c.set('sessionId',sid);const s=await c.get('db').session.findUnique({where:{id:sid},include:{user:true}});if(s&&s.expiresAt>new Date())c.set('user',s.user)}await next()});
app.get('/api/health',c=>c.json({ok:true,mode:'demo',storage:'Prisma + D1'}));
app.get('/api/bootstrap',async c=>{await seedCatalog(c.env);if(!c.get('user'))await createDemo(c);return c.json(await bootstrap(c))});
app.get('/api/products',async c=>{await seedCatalog(c.env);const q=c.req.query('q')??'',category=c.req.query('category');const list=await c.get('db').product.findMany({where:{...(category&&category!=='All'?{category}:{}),...(q?{OR:[{name:{contains:q}},{brand:{contains:q}}]}:{})},include:{_count:{select:{reviews:true}}}});return c.json(list.map(product))});
app.get('/api/shipping',c=>c.json(shippingMethods));app.get('/api/coupons',c=>c.json(coupons));
app.post('/api/auth/login',async c=>{const b=z.object({email,password,rememberMe:z.boolean().default(true)}).parse(await c.req.json());await limit(c,'login:'+b.email);const u=await c.get('db').user.findUnique({where:{email:b.email}});if(!u||!await verify(b.password,u.passwordHash))fail('Email or password is incorrect.',401);if(c.get('sessionId'))await c.get('db').session.deleteMany({where:{id:c.get('sessionId')}});await session(c,u.id,b.rememberMe);c.set('user',u);return c.json(await bootstrap(c))});
app.post('/api/auth/register',async c=>{const b=z.object({email,password,name:text(80),rememberMe:z.boolean().default(true)}).parse(await c.req.json());await limit(c,'register:'+b.email);const db=c.get('db');if(await db.user.findUnique({where:{email:b.email}}))fail('An account with this email already exists.',409);const guest=c.get('user');const data={email:b.email,passwordHash:await hash(b.password),name:b.name,guest:false};const u=guest?.guest?await db.user.update({where:{id:guest.id},data}):await db.user.create({data:{...data,id:id()}});if(c.get('sessionId'))await db.session.deleteMany({where:{id:c.get('sessionId')}});await session(c,u.id,b.rememberMe);c.set('user',u);return c.json(await bootstrap(c))});
app.post('/api/auth/demo-provider',async c=>{const b=z.object({provider:z.enum(['Google','Apple','Facebook'])}).parse(await c.req.json());if(c.get('user')){await notify(c,'Demo provider sign-in',`${b.provider} sign-in is simulated; no external account was connected.`,'/profile');return c.json(await bootstrap(c))}await seedCatalog(c.env);await createDemo(c,'Alex Morgan',b.provider);return c.json(await bootstrap(c))});
app.post('/api/auth/forgot',async c=>{const b=z.object({email,method:z.enum(['email','sms']).default('email')}).parse(await c.req.json());await limit(c,'forgot:'+b.email,5);const u=await c.get('db').user.findUnique({where:{email:b.email}});const code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0');const challengeId=id();await c.get('db').authChallenge.create({data:{id:challengeId,userId:u?.id??'unknown',type:'reset',value:await hash(code),expiresAt:new Date(Date.now()+10*60000)}});return c.json({challengeId,demoCode:code,message:`Demo ${b.method==='sms'?'SMS':'email'} delivery: use the code shown here. No message was sent.`})});
app.post('/api/auth/reset',async c=>{const b=z.object({challengeId:text(),code:pin,password}).parse(await c.req.json());const db=c.get('db');const ch=await db.authChallenge.findUnique({where:{id:b.challengeId}});if(!ch||ch.type!=='reset'||ch.expiresAt<new Date()||ch.attempts>=5)fail('This code has expired. Request a new one.');await db.authChallenge.update({where:{id:ch.id},data:{attempts:{increment:1}}});if(!await verify(b.code,ch.value))fail('The verification code is incorrect.');const u=await db.user.findUnique({where:{id:ch.userId}});if(!u)fail('No account matches this email. Create an account to continue.');await db.user.update({where:{id:u.id},data:{passwordHash:await hash(b.password)}});await db.authChallenge.delete({where:{id:ch.id}});await db.session.deleteMany({where:{userId:u.id}});await session(c,u.id);c.set('user',u);return c.json(await bootstrap(c))});
app.post('/api/auth/passkey/options',async c=>{const b=z.object({email}).parse(await c.req.json());await limit(c,'passkey:'+b.email);const db=c.get('db'),u=await db.user.findUnique({where:{email:b.email}});if(!u)fail('No passkey is available for this email.');const keys=await db.passkey.findMany({where:{userId:u.id}});if(!keys.length)fail('No passkey is available for this email.');const url=new URL(c.req.url);const options=await generateAuthenticationOptions({rpID:url.hostname,userVerification:'preferred',allowCredentials:keys.map(k=>({id:k.id,transports:parse(k.transports)}))});const challengeId=id();await db.authChallenge.create({data:{id:challengeId,userId:u.id,type:'passkey-login',value:JSON.stringify({challenge:options.challenge,origin:url.origin,rpID:url.hostname}),expiresAt:new Date(Date.now()+300000)}});return c.json({options,challengeId})});
app.post('/api/auth/passkey/verify',async c=>{const b=z.object({challengeId:text(),response:z.any()}).parse(await c.req.json());const db=c.get('db'),ch=await db.authChallenge.findUnique({where:{id:b.challengeId}});if(!ch||ch.type!=='passkey-login'||ch.expiresAt<new Date())fail('Passkey sign-in expired. Try again.');const key=await db.passkey.findFirst({where:{id:b.response?.id??'',userId:ch.userId}});if(!key)fail('This passkey does not belong to the account.',403);const expected=parse(ch.value,{}),result=await verifyAuthenticationResponse({response:b.response,expectedChallenge:expected.challenge,expectedOrigin:expected.origin,expectedRPID:expected.rpID,credential:{id:key.id,publicKey:bytes(key.publicKey),counter:key.counter,transports:parse(key.transports)},requireUserVerification:false});if(!result.verified)fail('Passkey verification failed.',403);await db.authChallenge.delete({where:{id:ch.id}});await db.passkey.update({where:{id:key.id},data:{counter:result.authenticationInfo.newCounter}});if(c.get('sessionId'))await db.session.deleteMany({where:{id:c.get('sessionId')}});await session(c,ch.userId);c.set('user',await db.user.findUniqueOrThrow({where:{id:ch.userId}}));return c.json(await bootstrap(c))});
app.use('/api/*',async(c,next)=>{if(!c.get('user'))fail('Please sign in to continue.',401);await next()});
app.post('/api/auth/logout',async c=>{if(c.get('sessionId'))await c.get('db').session.deleteMany({where:{id:c.get('sessionId')}});deleteCookie(c,'evira_session',{path:'/'});return c.json({ok:true})});
app.patch('/api/user',async c=>{const b=z.object({name:text(80).optional(),phone:z.string().max(30).optional(),birthDate:z.string().max(20).optional(),gender:z.string().max(30).optional()}).parse(await c.req.json());await c.get('db').user.update({where:{id:c.get('user').id},data:b});return c.json(await bootstrap(c))});
app.post('/api/user/email',async c=>{const b=z.object({email,password:z.string()}).parse(await c.req.json());const u=c.get('user');await limit(c,'email-change:'+u.id);if(u.guest)fail('Create an account first.');if(!await verify(b.password,u.passwordHash))fail('Your current password is incorrect.',403);const other=await c.get('db').user.findUnique({where:{email:b.email}});if(other&&other.id!==u.id)fail('This email is already registered.',409);await c.get('db').user.update({where:{id:u.id},data:{email:b.email}});await c.get('db').session.deleteMany({where:{userId:u.id,id:{not:c.get('sessionId')}}});return c.json(await bootstrap(c))});
app.patch('/api/settings',async c=>{const b=z.object({language:z.enum(['English','Khmer','Chinese']).optional(),general:z.boolean().optional(),sound:z.boolean().optional(),vibrate:z.boolean().optional(),promotions:z.boolean().optional(),updates:z.boolean().optional(),payment:z.boolean().optional(),biometric:z.boolean().optional(),rememberMe:z.boolean().optional(),invited:z.array(z.string().max(100)).max(50).optional()}).parse(await c.req.json());const u=c.get('user');await c.get('db').user.update({where:{id:u.id},data:{settings:JSON.stringify({...parse(u.settings,{}),...b})}});return c.json(await bootstrap(c))});
app.post('/api/user/avatar',async c=>{const type=c.req.header('Content-Type')??'';if(!['image/png','image/jpeg','image/webp'].includes(type))fail('Choose a PNG, JPEG or WebP image.');const content=await c.req.arrayBuffer();if(content.byteLength>2*1024*1024)fail('Choose an image smaller than 2 MB.');const data=new Uint8Array(content);const valid=type==='image/png'?data[0]===137&&data[1]===80:type==='image/jpeg'?data[0]===255&&data[1]===216:new TextDecoder().decode(data.slice(0,4))==='RIFF'&&new TextDecoder().decode(data.slice(8,12))==='WEBP';if(!valid)fail('This file is not a supported image.');const key='avatars/'+c.get('user').id;await c.env.BUCKET.put(key,content,{httpMetadata:{contentType:type}});await c.get('db').user.update({where:{id:c.get('user').id},data:{avatar:'/api/avatar/'+c.get('user').id+'?v='+Date.now()}});return c.json(await bootstrap(c))});
app.get('/api/avatar/:id',async c=>{if(c.req.param('id')!==c.get('user').id)fail('This image is private.',403);const object=await c.env.BUCKET.get('avatars/'+c.req.param('id'));if(!object)fail('Image not found.',404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType??'image/jpeg','Cache-Control':'private, max-age=60','X-Content-Type-Options':'nosniff'}})});
app.post('/api/security/pin',async c=>{const b=z.object({pin,currentPin:z.string().optional()}).parse(await c.req.json());await authorizePin(c,b.currentPin);await c.get('db').user.update({where:{id:c.get('user').id},data:{pinHash:await hash(b.pin)}});return c.json(await bootstrap(c))});
app.post('/api/security/password',async c=>{const b=z.object({currentPassword:z.string().optional(),password}).parse(await c.req.json());const u=c.get('user');if(u.passwordHash&&(!b.currentPassword||!await verify(b.currentPassword,u.passwordHash)))fail('Your current password is incorrect.',403);if(u.guest)fail('Create an account before setting a password.');await c.get('db').user.update({where:{id:u.id},data:{passwordHash:await hash(b.password)}});await c.get('db').session.deleteMany({where:{userId:u.id,id:{not:c.get('sessionId')}}});return c.json({ok:true})});
app.post('/api/passkeys/register/options',async c=>{const u=c.get('user'),url=new URL(c.req.url);if(u.guest)fail('Create an email account before adding a passkey.');const keys=await c.get('db').passkey.findMany({where:{userId:u.id}});const options=await generateRegistrationOptions({rpName:'Evira',rpID:url.hostname,userID:new TextEncoder().encode(u.id),userName:u.email,userDisplayName:u.name,attestationType:'none',excludeCredentials:keys.map((k:any)=>({id:k.id,transports:parse(k.transports)})),authenticatorSelection:{residentKey:'preferred',userVerification:'preferred'}});const challengeId=id();await c.get('db').authChallenge.create({data:{id:challengeId,userId:u.id,type:'passkey-register',value:JSON.stringify({challenge:options.challenge,origin:url.origin,rpID:url.hostname}),expiresAt:new Date(Date.now()+300000)}});return c.json({options,challengeId})});
app.post('/api/passkeys/register/verify',async c=>{const b=z.object({challengeId:text(),response:z.any()}).parse(await c.req.json()),db=c.get('db');const ch=await db.authChallenge.findUnique({where:{id:b.challengeId}});if(!ch||ch.userId!==c.get('user').id||ch.type!=='passkey-register'||ch.expiresAt<new Date())fail('Passkey setup expired. Try again.');const expected=parse(ch.value,{});const result=await verifyRegistrationResponse({response:b.response,expectedChallenge:expected.challenge,expectedOrigin:expected.origin,expectedRPID:expected.rpID,requireUserVerification:false});if(!result.verified||!result.registrationInfo)fail('Passkey verification failed.');const key=result.registrationInfo.credential;await db.passkey.create({data:{id:key.id,userId:ch.userId,publicKey:b64(key.publicKey),counter:key.counter,transports:JSON.stringify(key.transports??[])}});await db.authChallenge.delete({where:{id:ch.id}});return c.json(await bootstrap(c))});
app.delete('/api/passkeys',async c=>{await c.get('db').passkey.deleteMany({where:{userId:c.get('user').id}});return c.json(await bootstrap(c))});
app.post('/api/wishlist/:id',async c=>{const uid=c.get('user').id,pid=c.req.param('id');if(!await c.get('db').product.findUnique({where:{id:pid}}))fail('Product not found.',404);const where={userId_productId:{userId:uid,productId:pid}},existing=await c.get('db').wishlist.findUnique({where});if(existing)await c.get('db').wishlist.delete({where});else await c.get('db').wishlist.create({data:{userId:uid,productId:pid}});return c.json(await bootstrap(c))});
app.post('/api/cart',async c=>{const b=z.object({productId:text(),size:text(30),color:text(30),quantity:z.number().int().min(1).max(20)}).parse(await c.req.json());const p=await c.get('db').product.findUnique({where:{id:b.productId}});if(!p)fail('Product not found.',404);if(!parse(p.sizes).includes(b.size)||!parse(p.colors).includes(b.color))fail('Choose a valid size and color.');const uid=c.get('user').id;const current=await c.get('db').cartItem.findUnique({where:{userId_productId_size_color:{userId:uid,productId:p.id,size:b.size,color:b.color}}});if((current?.quantity??0)+b.quantity>Math.min(p.stock,20))fail('The requested quantity is not available.');await c.env.DB.batch([c.env.DB.prepare('INSERT INTO "CartItem" ("id","userId","productId","size","color","quantity") VALUES (?,?,?,?,?,?) ON CONFLICT ("userId","productId","size","color") DO UPDATE SET "quantity"="quantity"+excluded."quantity"').bind(id(),uid,p.id,b.size,b.color,b.quantity),c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(uid)]);return c.json(await bootstrap(c))});
app.patch('/api/cart/:id',async c=>{const b=z.object({quantity:z.number().int().min(1).max(20)}).parse(await c.req.json());const line=await c.get('db').cartItem.findFirst({where:{id:c.req.param('id'),userId:c.get('user').id},include:{product:true}});if(!line)fail('Cart item not found.',404);if(b.quantity>line.product.stock)fail('That quantity is not available.');await c.env.DB.batch([c.env.DB.prepare('UPDATE "CartItem" SET "quantity"=? WHERE "id"=? AND "userId"=?').bind(b.quantity,line.id,line.userId),c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(line.userId)]);return c.json(await bootstrap(c))});
app.delete('/api/cart/:id',async c=>{await c.env.DB.batch([c.env.DB.prepare('DELETE FROM "CartItem" WHERE "id"=? AND "userId"=?').bind(c.req.param('id'),c.get('user').id),c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(c.get('user').id)]);return c.json(await bootstrap(c))});
const addressSchema=z.object({label:text(30),recipient:text(80),phone:z.string().trim().min(6).max(30),line1:text(180),city:text(80),country:text(80),postalCode:z.string().max(20),latitude:z.number().min(-90).max(90).default(11.5564),longitude:z.number().min(-180).max(180).default(104.9282),isDefault:z.boolean().default(false)});
app.post('/api/addresses',async c=>{const b=addressSchema.parse(await c.req.json());const uid=c.get('user').id;const count=await c.get('db').address.count({where:{userId:uid}});if(count>=12)fail('You can save up to 12 addresses.');if(b.isDefault||count===0)await c.get('db').address.updateMany({where:{userId:uid},data:{isDefault:false}});await c.get('db').address.create({data:{...b,id:id(),userId:uid,isDefault:b.isDefault||count===0}});return c.json(await bootstrap(c))});
app.patch('/api/addresses/:id',async c=>{const b=addressSchema.parse(await c.req.json());const uid=c.get('user').id;const a=await c.get('db').address.findFirst({where:{id:c.req.param('id'),userId:uid}});if(!a)fail('Address not found.',404);if(b.isDefault)await c.get('db').address.updateMany({where:{userId:uid},data:{isDefault:false}});await c.get('db').address.update({where:{id:a.id},data:b});return c.json(await bootstrap(c))});
app.delete('/api/addresses/:id',async c=>{const uid=c.get('user').id;await c.get('db').address.deleteMany({where:{id:c.req.param('id'),userId:uid}});const left=await c.get('db').address.findMany({where:{userId:uid}});if(left.length&&!left.some((a:any)=>a.isDefault))await c.get('db').address.update({where:{id:left[0].id},data:{isDefault:true}});return c.json(await bootstrap(c))});
app.post('/api/payments',async c=>{const b=z.object({brand:z.enum(['Visa','Mastercard','PayPal','Google Pay','Apple Pay']),last4:z.string().regex(/^\d{4}$/),name:text(80),expiry:z.string().regex(/^\d{2}\/\d{2}$/)}).parse(await c.req.json());if(await c.get('db').paymentMethod.count({where:{userId:c.get('user').id}})>=10)fail('You can save up to 10 payment methods.');await c.get('db').paymentMethod.create({data:{...b,id:id(),userId:c.get('user').id}});return c.json(await bootstrap(c))});
app.delete('/api/payments/:id',async c=>{await c.get('db').paymentMethod.deleteMany({where:{id:c.req.param('id'),userId:c.get('user').id}});return c.json(await bootstrap(c))});
async function quote(c:any,input:any){const db=c.get('db'),uid=c.get('user').id;const cart=await db.cartItem.findMany({where:{userId:uid},include:{product:true}});if(!cart.length)fail('Your cart is empty.');for(const l of cart)if(l.quantity>l.product.stock)fail(`${l.product.name} does not have enough stock.`);const subtotal=cart.reduce((s:number,l:any)=>s+l.quantity*l.product.price,0);const method=shippingMethods.find(s=>s.id===input.shippingMethod)??shippingMethods[1];let shipping=method.price,discount=0;const code=(input.coupon??'').trim().toUpperCase();if(code){const cp=coupons.find(cp=>cp.code===code);if(!cp)fail('This promo code is not valid.');if(subtotal<cp.min)fail(`This offer needs a subtotal of $${(cp.min/100).toFixed(2)}.`);if(cp.firstOnly&&await db.order.count({where:{userId:uid,id:{not:{startsWith:'demo-'}},status:{not:'cancelled'}}}))fail('This offer is for your first order.');discount=Math.min(Math.round(subtotal*cp.percent/100),cp.max);if(code==='FREESHIP')shipping=0;}return{cart,subtotal,discount,shipping,total:subtotal-discount+shipping,coupon:code,shippingMethod:method.id}}
app.post('/api/checkout/quote',async c=>{const b=z.object({shippingMethod:z.string().optional(),coupon:z.string().max(40).optional()}).parse(await c.req.json());const q=await quote(c,b);return c.json({...q,cart:undefined})});
app.post('/api/checkout',async c=>{const b=z.object({addressId:text(),shippingMethod:z.enum(['economy','regular','cargo','express']),paymentMethod:text(),coupon:z.string().max(40).default(''),note:z.string().max(500).default(''),pin:z.string().optional(),idempotencyKey:z.string().uuid()}).parse(await c.req.json());const db=c.get('db'),uid=c.get('user').id;const existing=await db.order.findUnique({where:{userId_idempotencyKey:{userId:uid,idempotencyKey:b.idempotencyKey}}});if(existing)return c.json({order:order(existing),state:await bootstrap(c)});const address=await db.address.findFirst({where:{id:b.addressId,userId:uid}});if(!address)fail('Choose a saved delivery address.');const q=await quote(c,b);let method='Evira Wallet';if(b.paymentMethod==='wallet')await authorizePin(c,b.pin);else{const pm=await db.paymentMethod.findFirst({where:{id:b.paymentMethod,userId:uid}});if(!pm)fail('Choose a saved payment method.');method=`Demo ${pm.brand} •••• ${pm.last4}`;}
 const user=await db.user.findUniqueOrThrow({where:{id:uid}});if(b.paymentMethod==='wallet'&&user.balance<q.total)fail('Your wallet balance is too low. Top up or select another payment method.');const oid=id(),time=iso();const items=q.cart.map((l:any)=>({productId:l.product.id,name:l.product.name,image:l.product.image,price:l.product.price,size:l.size,color:l.color,quantity:l.quantity}));
 const statements=[c.env.DB.prepare('INSERT INTO "OperationGuard" ("id","valid") VALUES (?,(SELECT CASE WHEN "cartVersion"=? THEN 1 ELSE 0 END FROM "User" WHERE "id"=?))').bind(oid,user.cartVersion,uid),...q.cart.map((l:any)=>c.env.DB.prepare('UPDATE "Product" SET "stock"="stock"-?,"sold"="sold"+? WHERE "id"=?').bind(l.quantity,l.quantity,l.productId)),c.env.DB.prepare('INSERT INTO "Order" ("id","userId","cartVersion","idempotencyKey","status","items","subtotal","discount","shipping","total","address","shippingMethod","paymentMethod","coupon","note","events","createdAt","updatedAt") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(oid,uid,user.cartVersion,b.idempotencyKey,'placed',JSON.stringify(items),q.subtotal,q.discount,q.shipping,q.total,JSON.stringify(address),q.shippingMethod,method,q.coupon,b.note,JSON.stringify([{status:'placed',time,text:'Order placed — demo payment accepted'}]),time,time)];
 if(b.paymentMethod==='wallet'){statements.push(c.env.DB.prepare('UPDATE "User" SET "balance"="balance"-? WHERE "id"=?').bind(q.total,uid),c.env.DB.prepare('INSERT INTO "WalletTransaction" ("id","userId","title","amount","type","reference","createdAt") VALUES (?,?,?,?,?,?,?)').bind(id(),uid,'Shopping at Evira',-q.total,'payment',oid,time));}
 statements.push(c.env.DB.prepare('DELETE FROM "CartItem" WHERE "userId"=?').bind(uid),c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(uid),c.env.DB.prepare('DELETE FROM "OperationGuard" WHERE "id"=?').bind(oid),...(parse(user.settings,{}).general===false||parse(user.settings,{}).updates===false?[]:[c.env.DB.prepare('INSERT INTO "Notification" ("id","userId","title","text","read","link","createdAt") VALUES (?,?,?,?,?,?,?)').bind(id(),uid,'Order confirmed','Your demo order is placed. Follow its progress in My Orders.',0,'/orders/'+oid,time)]));
 try{await c.env.DB.batch(statements)}catch{const done=await db.order.findUnique({where:{userId_idempotencyKey:{userId:uid,idempotencyKey:b.idempotencyKey}}});if(done)return c.json({order:order(done),state:await bootstrap(c)});fail('Your cart or available stock changed. Review it and try again.',409)}return c.json({order:order(await db.order.findUniqueOrThrow({where:{id:oid}})),state:await bootstrap(c)},201)});
app.get('/api/orders/:id',async c=>{const o=await c.get('db').order.findFirst({where:{id:c.req.param('id'),userId:c.get('user').id}});if(!o)fail('Order not found.',404);return c.json(order(o))});
app.post('/api/orders/:id/advance',async c=>{const o=await c.get('db').order.findFirst({where:{id:c.req.param('id'),userId:c.get('user').id}});if(!o)fail('Order not found.',404);const steps=['placed','processing','shipped','delivered'];const next=steps[steps.indexOf(o.status)+1];if(!next)fail('This order has no next delivery step.');const moved=await c.get('db').order.updateMany({where:{id:o.id,userId:c.get('user').id,status:o.status},data:{status:next,updatedAt:new Date(),events:JSON.stringify([...parse(o.events),{status:next,time:iso(),text:{processing:'Parcel is being prepared',shipped:'Parcel is with the demo courier',delivered:'Parcel marked as received'}[next as 'processing']??next}])}});if(moved.count!==1)fail('The order changed. Refresh and try again.',409);await notify(c,next==='delivered'?'Order delivered':'Order update',`Demo order ${o.id.slice(0,8).toUpperCase()} is ${next}.`,'/orders/'+o.id);return c.json(await bootstrap(c))});
app.post('/api/orders/:id/cancel',async c=>{const db=c.get('db'),uid=c.get('user').id;const o=await db.order.findFirst({where:{id:c.req.param('id'),userId:uid}});if(!o)fail('Order not found.',404);if(o.status==='cancelled')return c.json(await bootstrap(c));if(!['placed','processing'].includes(o.status))fail('This parcel has already shipped. Contact support for a return.');const guard=id(),time=iso();const st=[c.env.DB.prepare('INSERT INTO "OperationGuard" ("id","valid") VALUES (?,(SELECT CASE WHEN "status" IN (\'placed\',\'processing\') THEN 1 ELSE 0 END FROM "Order" WHERE "id"=? AND "userId"=?))').bind(guard,o.id,uid),...(o.id.startsWith('demo-')?[]:parse(o.items)).map((l:any)=>c.env.DB.prepare('UPDATE "Product" SET "stock"="stock"+?,"sold"="sold"-? WHERE "id"=?').bind(l.quantity,l.quantity,l.productId)),c.env.DB.prepare('UPDATE "Order" SET "status"=?,"updatedAt"=?,"events"=? WHERE "id"=?').bind('cancelled',time,JSON.stringify([...parse(o.events),{status:'cancelled',time,text:'Order cancelled; demo payment refunded'}]),o.id)];if(o.paymentMethod==='Evira Wallet')st.push(c.env.DB.prepare('UPDATE "User" SET "balance"="balance"+? WHERE "id"=?').bind(o.total,uid),c.env.DB.prepare('INSERT INTO "WalletTransaction" ("id","userId","title","amount","type","reference","createdAt") VALUES (?,?,?,?,?,?,?)').bind(id(),uid,'Order refund',o.total,'refund','refund:'+o.id,time));st.push(c.env.DB.prepare('DELETE FROM "OperationGuard" WHERE "id"=?').bind(guard));try{await c.env.DB.batch(st)}catch{fail('The order changed. Refresh and try again.',409)}await notify(c,'Order cancelled','Your demo payment has been refunded.','/orders/'+o.id);return c.json(await bootstrap(c))});
app.post('/api/orders/:id/reorder',async c=>{const o=await c.get('db').order.findFirst({where:{id:c.req.param('id'),userId:c.get('user').id}});if(!o)fail('Order not found.',404);const uid=c.get('user').id,items=parse(o.items);const st=[];for(const item of items){const p=await c.get('db').product.findUnique({where:{id:item.productId}});if(!p||p.stock<item.quantity)fail(`${item.name} is unavailable.`);const current=await c.get('db').cartItem.findUnique({where:{userId_productId_size_color:{userId:uid,productId:p.id,size:item.size,color:item.color}}});if((current?.quantity??0)+item.quantity>20)fail('Your cart already has the maximum quantity for this item.');st.push(c.env.DB.prepare('INSERT INTO "CartItem" ("id","userId","productId","size","color","quantity") VALUES (?,?,?,?,?,?) ON CONFLICT ("userId","productId","size","color") DO UPDATE SET "quantity"="quantity"+excluded."quantity"').bind(id(),uid,p.id,item.size,item.color,item.quantity))}st.push(c.env.DB.prepare('UPDATE "User" SET "cartVersion"="cartVersion"+1 WHERE "id"=?').bind(uid));await c.env.DB.batch(st);return c.json(await bootstrap(c))});
app.post('/api/wallet/topup',async c=>{const b=z.object({amount:z.number().int().min(100).max(100000),paymentMethod:text(),pin:z.string().optional(),idempotencyKey:z.string().uuid()}).parse(await c.req.json());await authorizePin(c,b.pin);const uid=c.get('user').id,db=c.get('db');const pm=await db.paymentMethod.findFirst({where:{id:b.paymentMethod,userId:uid}});if(!pm)fail('Choose a saved demo payment method.');const existing=await db.walletTransaction.findUnique({where:{userId_reference:{userId:uid,reference:b.idempotencyKey}}});if(existing)return c.json(await bootstrap(c));try{await c.env.DB.batch([c.env.DB.prepare('INSERT INTO "WalletTransaction" ("id","userId","title","amount","type","reference","createdAt") VALUES (?,?,?,?,?,?,?)').bind(id(),uid,'Demo wallet top up',b.amount,'topup',b.idempotencyKey,iso()),c.env.DB.prepare('UPDATE "User" SET "balance"="balance"+? WHERE "id"=?').bind(b.amount,uid)])}catch{if(!await db.walletTransaction.findUnique({where:{userId_reference:{userId:uid,reference:b.idempotencyKey}}}))fail('Top up failed. Try again.',409);return c.json(await bootstrap(c))}await notify(c,'Top up successful','Demo funds were added to your wallet. No real card was charged.','/wallet');return c.json(await bootstrap(c))});
app.get('/api/products/:id/reviews',async c=>{const uid=c.get('user').id;const reviews=await c.get('db').review.findMany({where:{productId:c.req.param('id')},include:{user:{select:{name:true,avatar:true}}},orderBy:{createdAt:'desc'}});return c.json(reviews.map((r:any)=>({...r,liked:parse(r.likedBy).includes(uid),likedBy:undefined,verified:true})))});
app.post('/api/products/:id/reviews',async c=>{const b=z.object({rating:z.number().int().min(1).max(5),text:z.string().trim().min(5).max(1500)}).parse(await c.req.json());const db=c.get('db'),uid=c.get('user').id,pid=c.req.param('id');const delivered=await db.order.findMany({where:{userId:uid,status:'delivered'}});if(!delivered.some((o:any)=>parse(o.items).some((l:any)=>l.productId===pid)))fail('You can review this item after a delivered order.',403);await db.review.upsert({where:{userId_productId:{userId:uid,productId:pid}},create:{id:id(),userId:uid,productId:pid,...b},update:b});const avg=await db.review.aggregate({where:{productId:pid},_avg:{rating:true}});await db.product.update({where:{id:pid},data:{rating:avg._avg.rating??4.8}});return c.json({ok:true})});
app.post('/api/reviews/:id/like',async c=>{const r=await c.get('db').review.findUnique({where:{id:c.req.param('id')}});if(!r)fail('Review not found.',404);const uid=c.get('user').id,old=parse(r.likedBy) as string[],next=old.includes(uid)?old.filter(v=>v!==uid):[...old,uid];await c.get('db').review.update({where:{id:r.id},data:{likes:next.length,likedBy:JSON.stringify(next)}});return c.json({liked:next.includes(uid),likes:next.length})});
app.patch('/api/notifications',async c=>{const b=z.object({id:z.string().optional()}).parse(await c.req.json());await c.get('db').notification.updateMany({where:{userId:c.get('user').id,...(b.id?{id:b.id}:{})},data:{read:true}});return c.json(await bootstrap(c))});
app.get('/api/messages',async c=>{const channel=c.req.query('channel')??'support';if(channel!=='support'){const oid=channel.replace('courier:','');if(!await c.get('db').order.findFirst({where:{id:oid,userId:c.get('user').id}}))fail('Conversation not found.',404)}return c.json(await c.get('db').message.findMany({where:{userId:c.get('user').id,channel},orderBy:{createdAt:'asc'},take:200}))});
app.post('/api/messages',async c=>{const b=z.object({text:z.string().trim().min(1).max(2000),channel:z.string().max(80).default('support')}).parse(await c.req.json());const uid=c.get('user').id;if(b.channel!=='support'&&!await c.get('db').order.findFirst({where:{id:b.channel.replace('courier:',''),userId:uid}}))fail('Conversation not found.',404);await c.get('db').message.create({data:{id:id(),userId:uid,...b,sender:'user'}});const lower=b.text.toLowerCase();const reply=b.channel.startsWith('courier:')?'Demo courier: I have your delivery details. This is a simulated conversation; use the order timeline to advance delivery.':lower.includes('refund')||lower.includes('return')?'You can cancel an order before it ships from My Orders. A wallet payment is refunded automatically. For delivered items, I can record your return request here; this demo does not connect to a real return service.':lower.includes('track')||lower.includes('delivery')||lower.includes('order')?'Open My Orders and choose Track Order to see its progress. The delivery timeline is simulated, and you can move it forward with “Advance demo delivery”.':lower.includes('payment')||lower.includes('wallet')?'Wallet funds and payment methods are demo-only. Top up from My Wallet, or manage your saved demo cards in Profile → Payment. No real money is moved.':'Thanks for your message. I’m the Evira demo assistant, with automatic replies. I can help you find order tracking, wallet, refund and account options.';await c.get('db').message.create({data:{id:id(),userId:uid,channel:b.channel,text:reply,sender:'assistant'}});return c.json(await c.get('db').message.findMany({where:{userId:uid,channel:b.channel},orderBy:{createdAt:'asc'},take:200}))});
app.onError((err,c)=>{if(err instanceof HTTPException)return c.json({error:err.message},err.status);if(err instanceof z.ZodError)return c.json({error:err.issues[0]?.message??'Check the information and try again.',fields:err.issues.map(i=>({path:i.path.join('.'),message:i.message}))},400);console.error('Evira API error',err);return c.json({error:'Something went wrong. Your changes were not saved. Please try again.'},500)});
app.all('/api/*',c=>c.json({error:'This endpoint does not exist.'},404));
export default {async fetch(request:Request,env:Env,ctx:ExecutionContext){if(new URL(request.url).pathname.startsWith('/api/'))return app.fetch(request,env,ctx);if(env.ASSETS){let response=await env.ASSETS.fetch(request);if(response.status===404&&request.method==='GET'&&!new URL(request.url).pathname.split('/').at(-1)?.includes('.'))response=await env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));return response;}return new Response('Evira client is served by Vite during development.',{status:404})}};
