import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,CircleMarker} from 'leaflet';
import 'leaflet/dist/leaflet.css';
export function LocationMap({latitude,longitude,onChange}:{latitude:number;longitude:number;onChange?:(latitude:number,longitude:number)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),marker=useRef<CircleMarker|null>(null),callback=useRef(onChange),position=useRef({latitude,longitude});const[unavailable,setUnavailable]=useState(false);
 callback.current=onChange;position.current={latitude,longitude};
 useEffect(()=>{let cancelled=false;let observer:ResizeObserver|undefined;void import('leaflet').then(L=>{if(cancelled||!container.current)return;const p=position.current;const instance=L.map(container.current,{scrollWheelZoom:false,zoomControl:true}).setView([p.latitude,p.longitude],14);map.current=instance;L.tileLayer(import.meta.env.VITE_MAP_TILE_URL||'https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>setUnavailable(true)).addTo(instance);marker.current=L.circleMarker([p.latitude,p.longitude],{radius:9,color:'#fff',weight:3,fillColor:'#181818',fillOpacity:1}).addTo(instance);instance.on('click',event=>callback.current?.(Number(event.latlng.lat.toFixed(6)),Number(event.latlng.lng.toFixed(6))));observer=new ResizeObserver(()=>instance.invalidateSize());observer.observe(container.current);instance.invalidateSize()}).catch(()=>setUnavailable(true));return()=>{cancelled=true;observer?.disconnect();map.current?.remove();map.current=null;marker.current=null}},[]);
 useEffect(()=>{if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)return;marker.current?.setLatLng([latitude,longitude]);map.current?.panTo([latitude,longitude])},[latitude,longitude]);
 return<div className="location-map-wrap"><div ref={container} className="map-frame location-map" role="region" aria-label={onChange?'Choose delivery location on map':'Saved delivery location'}/>{onChange&&<p className="map-credit">Tap the map to move the location marker.</p>}{unavailable&&<p className="map-credit">Map tiles are unavailable. The saved coordinates are still usable.</p>}<a className="map-link" href={`https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}#map=15/${latitude}/${longitude}`} target="_blank" rel="noopener noreferrer">Open this location in OpenStreetMap ↗</a></div>
}
