import {useEffect,useState} from 'react';
import {Link,NavLink,Outlet,useLocation,useNavigate} from 'react-router-dom';
import {House,ShoppingBag,ClipboardList,Wallet,UserRound,Heart,Bell,Search,Menu,X,LogIn,ArrowRight,Sun,Moon} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {useApp} from '@/lib/store';
import {useT} from '@/lib/i18n';
import {IconButton,Modal} from './common';
const nav=[['/','Home',House],['/cart','Cart',ShoppingBag],['/orders','Orders',ClipboardList],['/wallet','Wallet',Wallet],['/profile','Profile',UserRound]]as const;
export function Brand({staticDisplay=false}:{staticDisplay?:boolean}){
 const location=useLocation(),mark=<><img src="/favicon.svg" alt=""/><span>evira<span className="brand-dot">.</span></span></>;
 return staticDisplay?<span className="brand" aria-label="Evira">{mark}</span>:<Link to="/story" className="brand" aria-label="Evira story" onClick={e=>{
  if(location.pathname==='/story'){e.preventDefault();window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
 }}>{mark}</Link>
}
export function Shell(){const {cart,user,notifications,theme,setTheme}=useApp(),t=useT(),location=useLocation(),navigate=useNavigate();const[q,setQ]=useState(''),[menu,setMenu]=useState(false);const count=cart?.reduce((s,l)=>s+l.quantity,0)??0,unread=notifications?.filter(n=>!n.read).length??0;useEffect(()=>{setMenu(false);window.scrollTo({top:0});const parts=location.pathname.split('/').filter(Boolean);const product=parts[0]==='products'?useApp.getState().products.find(p=>p.id===parts[1]):null;const title=product?.name??({orders:'My Orders',track:'Track Order',receipt:'E-Receipt',wallet:'My Wallet',profile:'Profile',catalog:'Shop',search:'Search',wishlist:'My Wishlist',checkout:'Checkout',cart:'My Cart',offers:'Special Offers',help:'Help Center',notifications:'Notifications',privacy:'Privacy Policy'} as Record<string,string>)[parts[0]]??'Evira';document.title=location.pathname==='/'?'Evira — Shop your way':title+' · Evira';},[location.pathname]);
 return<div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation"><NavLink to="/" end>{t('Home')}</NavLink><NavLink to="/catalog">{t('Catalog')}</NavLink><NavLink to="/offers">{t('Special Offers')}</NavLink></nav><form className="header-search" onSubmit={e=>{e.preventDefault();navigate('/search?q='+encodeURIComponent(q))}}><Search size={19}/><Input aria-label={t('Search products')} placeholder={t('Search products')} value={q} onChange={e=>setQ(e.target.value)}/></form><div className="header-actions"><IconButton label={t('My Wishlist')} onClick={()=>navigate('/wishlist')}><Heart size={22}/></IconButton><IconButton label={t('Notifications')} className="notification-control" onClick={()=>navigate('/notifications')}><Bell size={22}/>{unread>0&&<span className="notification-dot"/>}</IconButton><IconButton label={t('Cart')} className="cart-control" onClick={()=>navigate('/cart')}><ShoppingBag size={22}/>{count>0&&<span className="count-badge">{count}</span>}</IconButton><Link to="/profile" className="header-avatar" aria-label="Profile">{user?.avatar?<img src={user.avatar} alt=""/>:user?.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</Link><IconButton label="Open menu" className="mobile-menu-button" onClick={()=>setMenu(true)}><Menu size={22}/></IconButton></div></div></header><main id="main-content"><Outlet/></main><footer className="site-footer"><Brand/><span>Thoughtfully picked. Everyday favorites.</span><Link to="/help">{t('Help Center')}</Link><Link to="/privacy">{t('Privacy Policy')}</Link><span className="footer-demo">Interactive demo</span></footer><nav className="mobile-nav" aria-label="Main navigation">{nav.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==='/'}><span><Icon size={23}/>{path==='/cart'&&count>0&&<b>{count}</b>}</span><small>{t(label)}</small></NavLink>)}</nav><Modal open={menu} onOpenChange={setMenu} title="Explore Evira"><div className="menu-links">{[...nav,['/catalog','Catalog',ShoppingBag]as const,['/offers','Special Offers',ShoppingBag]as const,['/story','Our story',House]as const,['/wishlist','My Wishlist',Heart]as const,['/notifications','Notifications',Bell]as const].map(([path,label,Icon])=><Link key={path} to={path}><Icon size={20}/>{t(label)}</Link>)}<Button variant="outline" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>} {t('Dark Mode')}</Button></div></Modal></div>
}
